---
- name: Update TLS Certs
  hosts : all_servers
  gather_facts: False
  become : true
  tasks:
        
    - name: Template the certbot script
      ansible.builtin.template:
        src: certbot_renew.sh.j2
        dest: "/home/{{ ansible_user }}/containers/nginx/certbot_renew.sh"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0774


    - name: Template Linode DNS Credentails.
      template:
        src: linode.ini.j2
        dest: /var/lib/docker/volumes/letsencrypt-var/_data/credentials.ini
        owner: root
        group: root
        mode: 0600

    - name: Renew lets encrypt certs via Certbot.
      ansible.builtin.shell: 
        cmd: "/home/{{ ansible_user }}/containers/nginx/certbot_renew.sh"



