name: Trigger Update

on:
  workflow_dispatch:
    inputs:
      proxy_alias:
        description: 'Proxy to update'
        default: 'NULL'
        required: true
        type: string

jobs:
  Ansible_Update:
    name: Update the TLS certicate
    runs-on: ubuntu-latest
    steps:

    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Install Ansible
      run: pip3 install --break-system-packages ansible

    - name: Template the vault key
      run: echo '${{ secrets.ANSIBLE_VAULT_KEY }}' > .vaultkey

    - name: test the templateing 
      run: cat .vaultkey

    - name: Run Ansible Playbook
      env:
        ANSIBLE_HOST_KEY_CHECKING: False
        ANSIBLE_VAULT_PASSWORD_FILE: .vaultkey
      run: |
        ansible-playbook -i inventory/hosts.ini ${{ GITHUB_WORKSPACE }}/update_TLS.yml --limit ${{ github.event.inputs.proxy_alias }}      
