name: Trigger Update

on:
  workflow_dispatch:
    inputs:
      proxy_alias:
        description: 'Proxy to update'
        default: 'NULL'
        required: true
        type: string

jobs:
  Ansible_Update:
    name: Update the TLS certicate
    runs-on: ubuntu-latest
    steps:
    - name: Install Ansible
      run: pip3 --break-system-packages install ansible

    - name: Template the vault key
      run: echo ${{ secrets.ANSIBLE_VAULT_KEY }} > .vaultkey

    - name: Run Ansible Playbook
      env:
        ANSIBLE_HOST_KEY_CHECKING: False
        ANSIBLE_VAULT_PASSWORD_FILE: .vaultkey
      run: |
        ansible-playbook -i inventory/hosts.ini update_TLS.yml --limit ${{ github.event.inputs.proxy_alias }}      
